In [4]:
import pandas as pd

df = pd.read_csv(
    "../export_CAN_2022.csv",
    sep=",",
    low_memory=False
)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1071826
Columns: 75

In [5]:
df["ISO_COUNTRY_CODE"].value_counts()

ISO_COUNTRY_CODE
RO    209635
PL    194331
FR    119255
DE     98313
ES     81307
CZ     43700
LT     39981
IT     33911
BG     29856
SE     23918
SI     20478
LV     19841
HR     16627
HU     14935
GR     13706
FI     12742
NL     12403
DK     10645
PT     10501
BE     10167
EE      9844
SK      8019
AT      8011
NO      7294
UK      7241
IE      5175
CH      3743
MK      1924
LU      1651
CY      1165
MT      1095
IS       321
LI        91
Name: count, dtype: int64

In [6]:
austria_df = df[df["ISO_COUNTRY_CODE"] == "AT"].copy()

print("Austrian rows:", austria_df.shape[0])
print("Columns:", austria_df.shape[1])

Austrian rows: 8011
Columns: 75

In [7]:
austria_df.head()

,ID_NOTICE_CAN,TED_NOTICE_URL,YEAR,ID_TYPE,DT_DISPATCH,XSD_VERSION,CANCELLED,CORRECTIONS,B_MULTIPLE_CAE,CAE_NAME,...,NUMBER_OFFERS,NUMBER_TENDERS_SME,NUMBER_TENDERS_OTHER_EU,NUMBER_TENDERS_NON_EU,NUMBER_OFFERS_ELECTR,AWARD_EST_VALUE_EURO,AWARD_VALUE_EURO,AWARD_VALUE_EURO_FIN_1,B_SUBCONTRACTED,DT_AWARD
48,202268,ted.europa.eu/udl?uri=TED:NOTICE:68-2022:TEXT:...,2022,3,29/12/21,R209.S5,0,0,N,Bundesimmobiliengesellschaft m.b.H. vertreten ...,...,4.0,NaN,NaN,NaN,4.0,NaN,605498.00,605498.00,N,22/12/21
144,2022103,ted.europa.eu/udl?uri=TED:NOTICE:103-2022:TEXT...,2022,3,29/12/21,R209.S5,0,0,N,Salzburger Regionalstadtbahn Projektgesellscha...,...,3.0,1.0,NaN,NaN,3.0,NaN,2667082.11,2667082.11,N,03/12/21
568,2022570,ted.europa.eu/udl?uri=TED:NOTICE:570-2022:TEXT...,2022,3,29/12/21,R209.S5,0,0,N,REPUBLIK ÖSTERREICH vertreten durch die Bundes...,...,2.0,2.0,NaN,NaN,2.0,NaN,7550000.00,7550000.00,N,29/11/21
569,2022570,ted.europa.eu/udl?uri=TED:NOTICE:570-2022:TEXT...,2022,3,29/12/21,R209.S5,0,0,N,REPUBLIK ÖSTERREICH vertreten durch die Bundes...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2655,2022813,ted.europa.eu/udl?uri=TED:NOTICE:813-2022:TEXT...,2022,3,29/12/21,R209.S5,0,0,N,ACOmarket GmbH,...,1.0,NaN,NaN,1.0,1.0,NaN,339150.00,339150.00,N,29/11/21

In [8]:
austria_df.head()

,ID_NOTICE_CAN,TED_NOTICE_URL,YEAR,ID_TYPE,DT_DISPATCH,XSD_VERSION,CANCELLED,CORRECTIONS,B_MULTIPLE_CAE,CAE_NAME,...,NUMBER_OFFERS,NUMBER_TENDERS_SME,NUMBER_TENDERS_OTHER_EU,NUMBER_TENDERS_NON_EU,NUMBER_OFFERS_ELECTR,AWARD_EST_VALUE_EURO,AWARD_VALUE_EURO,AWARD_VALUE_EURO_FIN_1,B_SUBCONTRACTED,DT_AWARD
48,202268,ted.europa.eu/udl?uri=TED:NOTICE:68-2022:TEXT:...,2022,3,29/12/21,R209.S5,0,0,N,Bundesimmobiliengesellschaft m.b.H. vertreten ...,...,4.0,NaN,NaN,NaN,4.0,NaN,605498.00,605498.00,N,22/12/21
144,2022103,ted.europa.eu/udl?uri=TED:NOTICE:103-2022:TEXT...,2022,3,29/12/21,R209.S5,0,0,N,Salzburger Regionalstadtbahn Projektgesellscha...,...,3.0,1.0,NaN,NaN,3.0,NaN,2667082.11,2667082.11,N,03/12/21
568,2022570,ted.europa.eu/udl?uri=TED:NOTICE:570-2022:TEXT...,2022,3,29/12/21,R209.S5,0,0,N,REPUBLIK ÖSTERREICH vertreten durch die Bundes...,...,2.0,2.0,NaN,NaN,2.0,NaN,7550000.00,7550000.00,N,29/11/21
569,2022570,ted.europa.eu/udl?uri=TED:NOTICE:570-2022:TEXT...,2022,3,29/12/21,R209.S5,0,0,N,REPUBLIK ÖSTERREICH vertreten durch die Bundes...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2655,2022813,ted.europa.eu/udl?uri=TED:NOTICE:813-2022:TEXT...,2022,3,29/12/21,R209.S5,0,0,N,ACOmarket GmbH,...,1.0,NaN,NaN,1.0,1.0,NaN,339150.00,339150.00,N,29/11/21

In [9]:
austria_df[
    [
        "CAE_NAME",
        "CAE_TOWN",
        "WIN_NAME",
        "WIN_TOWN",
        "WIN_COUNTRY_CODE",
        "VALUE_EURO"
    ]
].head(10)

,CAE_NAME,CAE_TOWN,WIN_NAME,WIN_TOWN,WIN_COUNTRY_CODE,VALUE_EURO
48,Bundesimmobiliengesellschaft m.b.H. vertreten ...,Graz,Tischlerei Georg Grübler GmbH.,Graz,AT,605498.00
144,Salzburger Regionalstadtbahn Projektgesellscha...,Salzburg,Eder Brunnenbau GmbH,Fischamend,AT,2667082.00
568,REPUBLIK ÖSTERREICH vertreten durch die Bundes...,Wien,Wintex Apparel GmbH,Offenburg,DE,7550000.00
569,REPUBLIK ÖSTERREICH vertreten durch die Bundes...,Wien,NaN,NaN,NaN,7550000.00
2655,ACOmarket GmbH,Wien,Zoom Video Communications Inc,San Jose,US,339150.00
3839,Verein Tiroler Landesmuseum Ferdinandeum,Innsbruck,Marte.Marte Architekten ZT GmbH,Feldkirch,AT,4087233.21
4061,ÖBB-Werbung GmbH,Wien,NaN,NaN,NaN,NaN
4092,Veterinärmedizinische Universität Wien,Wien,Österreichische Mensen Betriebsgesellschaft m....,Wien,AT,7000000.00
4201,TIZ Landl - Grieskirchen GmbH,Grieskirchen,Swietelsky AG,Linz,AT,118754.31
4202,TIZ Landl - Grieskirchen GmbH,Grieskirchen,Allmetall Aluminium- und Stahlbau Gesellschaft...,Klagenfurt,AT,111664.00

In [10]:
project_df = austria_df[
    [
        "ID_NOTICE_CAN",
        "YEAR",
        "DT_DISPATCH",
        "CAE_NAME",
        "CAE_TOWN",
        "WIN_NAME",
        "WIN_TOWN",
        "WIN_COUNTRY_CODE",
        "TYPE_OF_CONTRACT",
        "CPV",
        "VALUE_EURO"
    ]
].copy()

print("Rows:", project_df.shape[0])
print("Columns:", project_df.shape[1])

project_df.head()

Rows: 8011
Columns: 11

,ID_NOTICE_CAN,YEAR,DT_DISPATCH,CAE_NAME,CAE_TOWN,WIN_NAME,WIN_TOWN,WIN_COUNTRY_CODE,TYPE_OF_CONTRACT,CPV,VALUE_EURO
48,202268,2022,29/12/21,Bundesimmobiliengesellschaft m.b.H. vertreten ...,Graz,Tischlerei Georg Grübler GmbH.,Graz,AT,W,45421000,605498.0
144,2022103,2022,29/12/21,Salzburger Regionalstadtbahn Projektgesellscha...,Salzburg,Eder Brunnenbau GmbH,Fischamend,AT,W,45120000,2667082.0
568,2022570,2022,29/12/21,REPUBLIK ÖSTERREICH vertreten durch die Bundes...,Wien,Wintex Apparel GmbH,Offenburg,DE,U,18143000,7550000.0
569,2022570,2022,29/12/21,REPUBLIK ÖSTERREICH vertreten durch die Bundes...,Wien,NaN,NaN,NaN,U,18143000,7550000.0
2655,2022813,2022,29/12/21,ACOmarket GmbH,Wien,Zoom Video Communications Inc,San Jose,US,U,48515000,339150.0

In [11]:
missing = project_df.isnull().sum()

missing

ID_NOTICE_CAN          0
YEAR                   0
DT_DISPATCH            0
CAE_NAME               0
CAE_TOWN               0
WIN_NAME            2643
WIN_TOWN            2645
WIN_COUNTRY_CODE    2643
TYPE_OF_CONTRACT       0
CPV                    0
VALUE_EURO          2100
dtype: int64

In [12]:
print("Duplicate rows:", project_df.duplicated().sum())

Duplicate rows: 2667

In [13]:
project_df["VALUE_EURO"].describe()

count    5.911000e+03
mean     3.246613e+07
std      1.267989e+08
min      1.000000e-02
25%      3.461051e+05
50%      1.273650e+06
75%      8.000000e+06
max      2.734663e+09
Name: VALUE_EURO, dtype: float64

In [14]:
duplicates = project_df[
    project_df.duplicated(keep=False)
].sort_values("ID_NOTICE_CAN")

duplicates.head(20)

,ID_NOTICE_CAN,YEAR,DT_DISPATCH,CAE_NAME,CAE_TOWN,WIN_NAME,WIN_TOWN,WIN_COUNTRY_CODE,TYPE_OF_CONTRACT,CPV,VALUE_EURO
8887,20224290,2022,31/12/21,Stadtgemeinde Bad Vöslau,Bad Vöslau,NaN,NaN,NaN,W,45324000,NaN
8888,20224290,2022,31/12/21,Stadtgemeinde Bad Vöslau,Bad Vöslau,NaN,NaN,NaN,W,45324000,NaN
8889,20224290,2022,31/12/21,Stadtgemeinde Bad Vöslau,Bad Vöslau,NaN,NaN,NaN,W,45324000,NaN
12921,20226372,2022,03/01/22,"Österreichischer Rundfunk, ORF",Wien,NaN,NaN,NaN,U,34100000,NaN
12922,20226372,2022,03/01/22,"Österreichischer Rundfunk, ORF",Wien,NaN,NaN,NaN,U,34100000,NaN
12923,20226372,2022,03/01/22,"Österreichischer Rundfunk, ORF",Wien,NaN,NaN,NaN,U,34100000,NaN
12924,20226372,2022,03/01/22,"Österreichischer Rundfunk, ORF",Wien,NaN,NaN,NaN,U,34100000,NaN
12925,20226372,2022,03/01/22,"Österreichischer Rundfunk, ORF",Wien,NaN,NaN,NaN,U,34100000,NaN
12926,20226372,2022,03/01/22,"Österreichischer Rundfunk, ORF",Wien,NaN,NaN,NaN,U,34100000,NaN
12927,20226372,2022,03/01/22,"Österreichischer Rundfunk, ORF",Wien,NaN,NaN,NaN,U,34100000,NaN
12928,20226372,2022,03/01/22,"Österreichischer Rundfunk, ORF",Wien,NaN,NaN,NaN,U,34100000,NaN
12929,20226372,2022,03/01/22,"Österreichischer Rundfunk, ORF",Wien,NaN,NaN,NaN,U,34100000,NaN
12930,20226372,2022,03/01/22,"Österreichischer Rundfunk, ORF",Wien,NaN,NaN,NaN,U,34100000,NaN
15800,20227123,2022,03/01/22,Auftraggeber sind die Republik Österreich (Bun...,Wien,Toyota Material Handling Austria,Wiener Neudorf,AT,U,42415000,81900000.0
15801,20227123,2022,03/01/22,Auftraggeber sind die Republik Österreich (Bun...,Wien,Toyota Material Handling Austria,Wiener Neudorf,AT,U,42415000,81900000.0
15802,20227123,2022,03/01/22,Auftraggeber sind die Republik Österreich (Bun...,Wien,Toyota Material Handling Austria,Wiener Neudorf,AT,U,42415000,81900000.0
15803,20227123,2022,03/01/22,Auftraggeber sind die Republik Österreich (Bun...,Wien,Toyota Material Handling Austria,Wiener Neudorf,AT,U,42415000,81900000.0
16112,20227194,2022,03/01/22,Österreichische Agentur für Gesundheit und Ern...,Wien,NaN,NaN,NaN,U,24300000,NaN
16113,20227194,2022,03/01/22,Österreichische Agentur für Gesundheit und Ern...,Wien,NaN,NaN,NaN,U,24300000,NaN
16114,20227194,2022,03/01/22,Österreichische Agentur für Gesundheit und Ern...,Wien,NaN,NaN,NaN,U,24300000,NaN

In [15]:
df[df["ID_NOTICE_CAN"] == 20227123][
    [
        "ID_NOTICE_CAN",
        "ID_LOT",
        "ID_AWARD",
        "CAE_NAME",
        "WIN_NAME",
        "VALUE_EURO"
    ]
]

,ID_NOTICE_CAN,ID_LOT,ID_AWARD,CAE_NAME,WIN_NAME,VALUE_EURO
15800,20227123,1,13867232.0,Auftraggeber sind die Republik Österreich (Bun...,Toyota Material Handling Austria,81900000.0
15801,20227123,2,13867233.0,Auftraggeber sind die Republik Österreich (Bun...,Toyota Material Handling Austria,81900000.0
15802,20227123,3,13867234.0,Auftraggeber sind die Republik Österreich (Bun...,Toyota Material Handling Austria,81900000.0
15803,20227123,4,13867235.0,Auftraggeber sind die Republik Österreich (Bun...,Toyota Material Handling Austria,81900000.0
15804,20227123,5,13867236.0,Auftraggeber sind die Republik Österreich (Bun...,Linde Material Handling Austria GmbH,81900000.0
15805,20227123,6,13867237.0,Auftraggeber sind die Republik Österreich (Bun...,NaN,81900000.0

In [16]:
project_df = austria_df[
    [
        "ID_NOTICE_CAN",
        "ID_LOT",
        "ID_AWARD",
        "YEAR",
        "DT_DISPATCH",
        "CAE_NAME",
        "CAE_TOWN",
        "WIN_NAME",
        "WIN_TOWN",
        "WIN_COUNTRY_CODE",
        "TYPE_OF_CONTRACT",
        "CPV",
        "VALUE_EURO"
    ]
].copy()

print("Rows:", project_df.shape[0])
print("Columns:", project_df.shape[1])
print("Exact duplicate rows:", project_df.duplicated().sum())

Rows: 8011
Columns: 13
Exact duplicate rows: 0

In [17]:
project_df["CAE_NAME_CLEAN"] = (
    project_df["CAE_NAME"]
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

project_df["WIN_NAME_CLEAN"] = (
    project_df["WIN_NAME"]
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

In [18]:
project_df[
    [
        "CAE_NAME",
        "CAE_NAME_CLEAN",
        "WIN_NAME",
        "WIN_NAME_CLEAN"
    ]
].head(20)

,CAE_NAME,CAE_NAME_CLEAN,WIN_NAME,WIN_NAME_CLEAN
48,Bundesimmobiliengesellschaft m.b.H. vertreten ...,bundesimmobiliengesellschaft m.b.h. vertreten ...,Tischlerei Georg Grübler GmbH.,tischlerei georg grübler gmbh.
144,Salzburger Regionalstadtbahn Projektgesellscha...,salzburger regionalstadtbahn projektgesellscha...,Eder Brunnenbau GmbH,eder brunnenbau gmbh
568,REPUBLIK ÖSTERREICH vertreten durch die Bundes...,republik österreich vertreten durch die bundes...,Wintex Apparel GmbH,wintex apparel gmbh
569,REPUBLIK ÖSTERREICH vertreten durch die Bundes...,republik österreich vertreten durch die bundes...,NaN,NaN
2655,ACOmarket GmbH,acomarket gmbh,Zoom Video Communications Inc,zoom video communications inc
3839,Verein Tiroler Landesmuseum Ferdinandeum,verein tiroler landesmuseum ferdinandeum,Marte.Marte Architekten ZT GmbH,marte.marte architekten zt gmbh
4061,ÖBB-Werbung GmbH,öbb-werbung gmbh,NaN,NaN
4092,Veterinärmedizinische Universität Wien,veterinärmedizinische universität wien,Österreichische Mensen Betriebsgesellschaft m....,österreichische mensen betriebsgesellschaft m....
4201,TIZ Landl - Grieskirchen GmbH,tiz landl - grieskirchen gmbh,Swietelsky AG,swietelsky ag
4202,TIZ Landl - Grieskirchen GmbH,tiz landl - grieskirchen gmbh,Allmetall Aluminium- und Stahlbau Gesellschaft...,allmetall aluminium- und stahlbau gesellschaft...
4205,TIZ Landl - Grieskirchen GmbH,tiz landl - grieskirchen gmbh,Waizenauer Bauunternehmen GmbH & Co KG,waizenauer bauunternehmen gmbh & co kg
4248,Republik Österreich (Bund),republik österreich (bund),Meditrade GmbH.,meditrade gmbh.
7144,Republik Österreich (Bund),republik österreich (bund),Fracht FWO GmbH Wien,fracht fwo gmbh wien
7150,WWP Wiener Wohnbau Projektmanagement GmbH,wwp wiener wohnbau projektmanagement gmbh,Delta Baumanagement GmbH,delta baumanagement gmbh
7587,Bundesrechenzentrum GmbH,bundesrechenzentrum gmbh,Oracle Austria GmbH,oracle austria gmbh
7601,EBG MedAustron GmbH,ebg medaustron gmbh,BEC GmbH,bec gmbh
8885,Stadtgemeinde Bad Vöslau,stadtgemeinde bad vöslau,NaN,NaN
8886,Stadtgemeinde Bad Vöslau,stadtgemeinde bad vöslau,NaN,NaN
8887,Stadtgemeinde Bad Vöslau,stadtgemeinde bad vöslau,NaN,NaN
8888,Stadtgemeinde Bad Vöslau,stadtgemeinde bad vöslau,NaN,NaN

In [19]:
print("Unique contracting authorities:",
      project_df["CAE_NAME_CLEAN"].nunique())

print("Unique winning companies:",
      project_df["WIN_NAME_CLEAN"].nunique())

Unique contracting authorities: 849
Unique winning companies: 3017

In [21]:
project_df.groupby(
    ["CAE_NAME_CLEAN", "WIN_NAME_CLEAN"]
).size().sort_values(ascending=False).head(20)

CAE_NAME_CLEAN                                                                                                                                                                                                                                      WIN_NAME_CLEAN
stadt wien - ma 01 - wien digital                                                                                                                                                                                                                   rv-partner 1                                            31
                                                                                                                                                                                                                                                    rv-partner 2                                            28
                                                                                                                                                                                                                                                    rv-partner 3                                            24
verein österreich werbung                                                                                                                                                                                                                           google ireland limited                                  23
auftraggeber sind die republik österreich (bund), die bundesbeschaffung gmbh sowie alle weiteren auftraggeber gemäß der den ausschreibungsunterlagen beiliegenden kundenliste, im vergabeverfahren alle vertreten durch die bundesbeschaffung gmbh  consileon business consultancy gmbh                     17
                                                                                                                                                                                                                                                    omv downstream gmbh                                     16
                                                                                                                                                                                                                                                    bechtle gmbh                                            16
arbeitsmarktservice kärnten                                                                                                                                                                                                                         kärntner berufsförderungsinstitut gmbh                  15
auftraggeber sind die republik österreich (bund), die bundesbeschaffung gmbh sowie alle weiteren auftraggeber gemäß der den ausschreibungsunterlagen beiliegenden kundenliste, im vergabeverfahren alle vertreten durch die bundesbeschaffung gmbh  atos it solutions and services                          15
landeskrankenanstalten-betriebsgesellschaft - kabeg                                                                                                                                                                                                 eurogast kärntner legro                                 15
wiener gesundheitsverbund – serviceeinheit einkauf (see)                                                                                                                                                                                            atos it solutions and services gmbh                     15
auftraggeber sind die republik österreich (bund), die bundesbeschaffung gmbh sowie alle weiteren auftraggeber gemäß der den ausschreibungsunterlagen beiliegenden kundenliste, im vergabeverfahren alle vertreten durch die bundesbeschaffung gmbh  prosac prodcutos sl                                     14
wip wiener infrastruktur projekt gmbh                                                                                                                                                                                                               rahmenvereinbarungspartner                              14
auftraggeber sind die republik österreich (bund), die bundesbeschaffung gmbh sowie alle weiteren auftraggeber gemäß der den ausschreibungsunterlagen beiliegenden kundenliste, im vergabeverfahren alle vertreten durch die bundesbeschaffung gmbh  bernhard kohl sporthandel gmbh                          14
arbeitsmarktservice kärnten                                                                                                                                                                                                                         wifi kärnten gmbh                                       14
                                                                                                                                                                                                                                                    berufsförderungsinstitut kärnten                        13
wirtschaftskammer wien                                                                                                                                                                                                                              ferdinand berger & söhne gmbh                           12
autobahnen und schnellstrassen finanzierungs aktiengesellschaft                                                                                                                                                                                     schneeconcorde sommer und winterdienstleistungs gmbh    12
vereinigte bühnen wien gmbh                                                                                                                                                                                                                         lambert hofer 1862 gmbh                                 12
asfinag service gmbh                                                                                                                                                                                                                                kittinger ges.m.b.h.                                    12
dtype: int64

In [22]:
suspicious = project_df[
    project_df["WIN_NAME_CLEAN"].str.contains(
        "partner|rahmenvereinbarung",
        case=False,
        na=False
    )
]

suspicious["WIN_NAME_CLEAN"].value_counts().head(30)

WIN_NAME_CLEAN
rv-partner 1                                                                                                                                                                                                                         31
rv-partner 2                                                                                                                                                                                                                         28
rv-partner 3                                                                                                                                                                                                                         24
rahmenvereinbarungspartner                                                                                                                                                                                                           14
gemäß § 61 abs 4 bvergg erfolgt keine bekanntgabe der partner der rahmenvereinbarung                                                                                                                                                  8
lechner & partner zt gmbh                                                                                                                                                                                                             6
rv-partner 1 (keine angabe aus gründen des wettbewerbs)                                                                                                                                                                               6
rv-partner 2 (keine angabe aus gründen des wettbewerbs)                                                                                                                                                                               6
identität des rahmenvereinbarungspartners / zuschlagsempfängers wird aus wettbewerbsgründen nicht offen gelegt                                                                                                                        6
zimmermann, kuss & partner                                                                                                                                                                                                            5
rahmenvereinbarung mit mehreren partnern                                                                                                                                                                                              5
rv-partner 3 (keine angabe aus gründen des wettbewerbs)                                                                                                                                                                               4
spirk + partner ingenieur gmbh                                                                                                                                                                                                        4
baumeister schenk & partner gesmbh                                                                                                                                                                                                    4
identitäten der rahmenvereinbarungspartnerinnen werden aus wettbewerbsgründen nicht offen gelegt                                                                                                                                      4
rv-partner 4                                                                                                                                                                                                                          3
rv-partner 5                                                                                                                                                                                                                          3
fcp fritsch, chiari & partner zt gmbh                                                                                                                                                                                                 3
es wurden mit 3 firmen (alle kmu) jeweils eine rahmenvereinbarung abgeschlossen                                                                                                                                                       3
da es sich um eine rahmenvereinbarung mit mehreren unternehmen handelt, erfolgt gemäß § 61 abs 4 bvergg zur wahrung des fairen und lauteren wettbewerbs keine bekanntgabe der namen der partner der rahmenvereinbarung für los 2.     3
zieritz & partner zt gmbh                                                                                                                                                                                                             2
kratzer & partner zt gmbh                                                                                                                                                                                                             2
igt geotechnik und tunnelbau zt gmbh---il - ingenieurbüro laabmayr & partner zt gesmbh                                                                                                                                                2
air partner international gmbh                                                                                                                                                                                                        2
arge b2m baumanagement gmbh / hirm & partner zt gmbh                                                                                                                                                                                  2
ibk ingenieurbüro kronawetter gmbh---zimmermann, kuss & partner zt gmbh                                                                                                                                                               2
bietergemeinschaft ingenieure öhlinger + partner zt ges.m.b.h. / isp ziviltechniker gmbh---isp ziviltechniker gmbh                                                                                                                    2
metz & partner baumanagement ziviltechniker gesmbh                                                                                                                                                                                    2
identität des rahmenvereinbarungspartners wird aus wettbewerbsgründen nicht offen gelegt                                                                                                                                              2
at solution partner edv-beratungs- & vertriebs gmbh                                                                                                                                                                                   2
Name: count, dtype: int64

In [23]:
placeholder_patterns = [
    r"^rv-partner",
    r"^rahmenvereinbarungspartner$",
    r"keine bekanntgabe",
    r"nicht offen gelegt",
    r"identität.*nicht",
    r"identitäten.*nicht",
    r"rahmenvereinbarung mit mehreren partnern",
    r"es wurden mit .* firmen"
]

pattern = "|".join(placeholder_patterns)

project_df["IS_PLACEHOLDER_WINNER"] = (
    project_df["WIN_NAME_CLEAN"]
    .str.contains(pattern, regex=True, na=False)
)

print(
    project_df["IS_PLACEHOLDER_WINNER"].value_counts()
)

IS_PLACEHOLDER_WINNER
False    7853
True      158
Name: count, dtype: int64